### ISSUE TITLE
Question: vagrant-ignition plugin

### ISSUE THREAD

**Issue by kshpytsya** [mihailutasu/vagrant-fedora-coreos#1]
Hello Mihai,

Thank you for making an up-to-date Vargant box of Fedora CoreOS available.
I have been able to get it running using the following `Vagrantfile` (note the commented out lines):

```
Vagrant.configure("2") do |config|
  config.vm.hostname = "coreos"

  config.vm.box = "mihailutasu/fedora-coreos-stable"
  config.vm.box_version = "20200622.0.0"

  PRIVATE_IP = "192.168.60.10"

  config.vm.network "private_network", ip: PRIVATE_IP, auto_config: false

  config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 1]

    # config.ignition.config_obj = vb
  end

  # config.ignition.enabled = true

  config.vm.synced_folder ".", "/run/host"

  config.vm.provision "shell", inline: <<~END
    nmcli connection add type "ethernet" ifname "eth1" con-name "intnet" autoconnect "yes" ip4 "#{PRIVATE_IP}/24"
    nmcli connection modify intnet ipv6.method "disabled"
    nmcli connection up intnet
    systemctl restart NetworkManager-wait-online
  END
end
```

The shell provisioning block is something that I have managed to come up with to get the `eth1` adapter properly configured. However, it is my understanding that a proper way to achieve that would be via Ignition configuration which is also a proper way to perform all other aspects of OS customization and would be shareable between Vargant-based local dev environment and production deployment on actual servers (be it in some cloud or on own hardware).
I have tried the [vagrant-ignition](https://github.com/coreos/vagrant-ignition) plugin but enabling it (via uncommenting commented lines in the `Vagrantfile`) leads to VM being stuck with `FATAL: Could not read from the boot medium! System halted.` message in VM's console (as seen by pressing VirtualBox Manager "Show" button). I see that plugin creates `config.ign.merged`, `config.img`, and `config.vmdk` files, and `config.vmdk` is attached to VirtualBox VM as an IDE drive (the CoreOS image itself is attached as a SATA drive).

```
$ file config.img
config.img: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x0,0,1), end-CHS (0x3ff,254,63), startsector 1, 2999 sectors, extended partition table (last)

$ fdisk -l config.img
Disk config.img: 1.48 MiB, 1536000 bytes, 3000 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C89E4452-AAF1-67D0-8299-E7651D2805A8

Device      Start   End Sectors   Size Type
config.img1  2048  2966     919 459.5K Linux filesystem

$ sudo losetup -P /dev/loop0 config.img
$ sudo cat /dev/loop0p1
{"ignition":{"version":"2.0.0","config":{}},"storage":{},"networkd":{},"passwd":{"users":[{"name":"core","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"]}]}}
$ sudo losetup -d /dev/loop0
```

I am not partial to `vagrant-ignition` plugin per se but am rather looking for some practical solution of supplying Ignition configuration to CoreOS VM which would not require rebuilding entire OS box. I hope that you may have some ideas.

My software:
```
$ vboxmanage --version
6.1.10_Gentoor138449
$ vagrant --version
Vagrant 2.2.9
```

**Comment by mihailutasu** [comment]
Hello,

The vagrant-ignition plugin is not necessary (it is written for the old CoreOS). The ignition file was already applied during the build of the vagrant box. If you want to modify it, you can find in "utils" folder a yml file, and you can update it. Then run the script in that folder and you'll have the new ignition file, that will be provisioned when you build the box.

If you want to apply a new ignition file to the machine, I don't think it's possible. 
You could make a script that runs every time the system boots (you have to modify the ign file) that downloads some variables from a webserver, and apply them locally.
